<?php
/*
 * Created by PhpStorm.
 * User: denismoroz
 * Date: 27.03.18
 * Time: 21:06/home/denismoroz/PhpstormProjects/work_with_db
 */

class Object_db
{
    protected function __construct($host = "127.0.0.1", $user = "root", $pwd = "", $db = "my_db")
    {
        $this->HOST_ADDRESS = $host;
        $this->USERNAME = $user;
        $this->PASSWORD = $pwd;
        $this->DATABASE = $db;

        $this->mysqli = mysqli_init();
        $this->mysqli->options(MYSQLI_OPT_INT_AND_FLOAT_NATIVE, 1);
        $this->mysqli->real_connect($this->HOST_ADDRESS, $this->USERNAME, $this->PASSWORD,
            $this->DATABASE);


        if ($this->mysqli->connect_errno) {
            echo "Ошибка: Не удалось создать соединение с базой MySQL и вот почему: \n";
            echo "Номер_ошибки: " . $this->mysqli->connect_errno . "\n";
            echo "Ошибка: " . $this->mysqli->connect_error . "\n";
            exit();
        }
        echo "<i> Соединение установлено! </i>" . PHP_EOL;


        }

    protected function setCode($code)
        {
        $this->mysqli->query("set names {$code}");

        }


    protected function __destruct()
    {
        // TODO: Implement __destruct() method.

        $this->mysqli->close();
        echo "<i> Соединение закрыто! </i> \n";

    }
}

class Object_query extends Object_db {
    public function __construct(string $host = "127.0.0.1", string $user = "root",
                                 string $pwd = "", string $db = "my_db")
    {
        parent::__construct($host, $user, $pwd, $db);
    }

    public function table_desc($table)
    {

        $query = "describe {$table}";

        if (!$this->result = $this->mysqli->query($query)) {
            echo "Ошибка: Наш запрос не удался и вот почему: \n";
            echo "Запрос: " . $query . "\n";
            echo "Номер_ошибки: " . $this->mysqli->errno . "\n";
            echo "Ошибка: " . $this->mysqli->error . "\n";
            exit;
        }
            echo "<h3>Структура таблицы {$table}</h3>";
            echo '<table border="1px solid black" cellpadding="5px">';
            echo '<tr>';
            echo '<th>Field</th>';
            echo '<th>Type</th>';
            echo '<th>Null</th>';
            echo '<th>Key</th>';
            echo '<th>Default</th>';
            echo '<th>Extra</th>';
            echo '</tr>';
            for ($row = 0;$row <=$this->result->num_rows;$row++) {

                $this->result->data_seek($row);
                $goodsQuery = $this->result->fetch_assoc();
                echo '<tr>';
                echo '<td>'.print_r($goodsQuery["Field"],1).'</td>';
                echo '<td>'.print_r($goodsQuery["Type"],1).'</td>';
                echo '<td>'.print_r($goodsQuery["Null"],1).'</td>';
                echo '<td>'.print_r($goodsQuery["Key"],1).'</td>';
                echo '<td>'.print_r($goodsQuery["Default"],1).'</td>';
                echo '<td>'.print_r($goodsQuery["Extra"],1).'</td>';

                echo '</tr>';
        }
    }


    public function getSelect()
    {
        $resultTables = $this->mysqli->query("show tables");
        echo '<form action="" method="post">';
        echo '<br><label for="table">Доступные таблицы: </label>';
        echo '<select name="table" id="table">';
        for ($row = 0;$row <=$resultTables->num_rows;$row++) {

            $resultTables->data_seek($row);
            $table = $resultTables->fetch_assoc();
            echo '<option>'.print_r(array_pop($table),1).'</option>';
        }
        echo '</select><br>';
        echo '<input hidden name="form" value="description">';
        echo '<input type="submit" value="Смотреть структуру">';
        echo '</form>';


    }

    public function __destruct()
    {
        $this->result->free();
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

}

